### ISSUE TITLE
Suggestion: label the data

### ISSUE THREAD

**Issue by aito123** [pachamaltese/censo2017#15]
Hello thanks very much for this package, really help me fact checking some Chile tables from 2017. I was wondering if you are considering labelling the data like in a SPSS .sav format. In that way one could use the labels within the data without needing the code dictionary. I think is a good practice. The downside may be that it could make the data heavier but I think is a reasonable tradeoff.

Let me know, again thanks for this package.
Santiago from Perú

Ps. labelling like in haven_labelled style.

**Comment by pachadotdev** [comment]
Hi @aito123 
That would be hard to obtain with the current SQL backend, unless we convert the data once you run the `collect()` function.
Please consider that this package includes the tables "variables" and "variables_codificacion", so we can do a left join and get the labels as a character column.
