### ISSUE TITLE
Add software review badge

### ISSUE THREAD

**Issue by maelle** [pachamaltese/censo2017#4]
@pachamaltese sorry I clicked too rapidly and made a commit to main instead of a PR https://github.com/ropensci/censo2017/commit/3222e05cef355935600391155f4f6a4e381ba03a

Could you please knit the README for adding the badge? Sorry again.

**Comment by maelle** [comment]
Actually the badge should be

`[![Status at rOpenSci Software Peer Review](https://badges.ropensci.org/414_status.svg)](https://github.com/ropensci/software-review/issues/414)`

**Comment by maelle** [comment]
Furthermore, can you confirm you had seen 

> Should you want to acknowledge your reviewers in your package DESCRIPTION, you can do so by making them `"rev"`-type contributors in the `Authors@R` field (with their consent).  More info on this [here](https://devguide.ropensci.org/building.html#authorship).

And therefore chose not to? No judgement either way, I'm asking as I'm collecting info for the newsletter.

**Comment by pachadotdev** [comment]
Dear Dr. Salmon

Thanks a lot. I'm slowly back into normal activity after medical rest.

Of course I'm creating the MD file again. The authors were added as rev, after asking them.

Best,
M Vargas
