### ISSUE TITLE
need to add codecov token

### ISSUE THREAD

**Issue by pachadotdev** [pachamaltese/censo2017#5]
Dr @maelle 

I've asked to Dr @melvidoni, as gh-actions show the message "Could not find a repository associated with upload token ***", and therefore no code coverage is shown after transferring the repository.

How can I add a token? on my other repositories (i.e. pachamaltese/tradepolicy) I see this not on ropensci/censo2017
![image](https://user-images.githubusercontent.com/10091065/118899154-2b145200-b8dc-11eb-9cac-b23b74f550ca.png)

**Comment by maelle** [comment]
I think it is because you were given the "Maintain" role, not "Admin" role, for this repo. I have now given you "Admin" role.
